CREATE DATABASE IF NOT EXISTS app3;

USE app3;

CREATE TABLE IF NOT EXISTS login (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30),
  email VARCHAR(100),
  password VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS address (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  line1 VARCHAR(100),
  line2 VARCHAR(100),
  city VARCHAR(30),
  state VARCHAR(20),
  zipCode INT (20),
  phone INT (30)
);

CREATE TABLE IF NOT EXISTS credit (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  credit INT(100),
  date VARCHAR(100),
  cvv VARCHAR(30),
  billingZip VARCHAR(20)
);
